import "./globals.css";
import { Inter } from "next/font/google";
import SupabaseProvider from "./supabase-provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Extremely Advanced Ecommerce (Maybe)",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  header,
}: {
  children: React.ReactNode;
  header: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <SupabaseProvider>
          {header}
          {children}
        </SupabaseProvider>
      </body>
    </html>
  );
}
